 # Copyright (c) 2022, salesforce.com, inc.
 # All rights reserved.
 # SPDX-License-Identifier: BSD-3-Clause
 # For full license text, see the LICENSE file in the repo root or https://opensource.org/licenses/BSD-3-Clause

datasets:
  coco_caption: # name of the dataset builder
    dataset_card: dataset_card/coco_caption.md
    # data_dir: ${env.data_dir}/datasets
    data_type: images # [images|videos|features]

    build_info:
      # Be careful not to append minus sign (-) before split to avoid itemizing
      annotations:
        train:
          url: /mnt/data/coco/annotations/coco_vg.json
          storage: coco/annotations/coco_vg.json
        val:
          url: /mnt/data/coco/annotations/coco_vg_val.json
          storage:  coco/annotations/coco_vg_val.json
        test:
          url: /mnt/data/coco/annotations/coco_vg_test.json
          storage: coco/annotations/coco_vg_test.json

      images:
        url: /mnt/data/coco/images/
        storage: coco/images/
